default_language_version:
    python: python3.10
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: trailing-whitespace
            exclude: .bumpversion.cfg|notebooks/.*\.py
          - id: check-ast
          - id: check-added-large-files
          - id: check-toml
          - id: check-json
          - id: check-yaml


    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.6.9
      hooks:
        # E1131: unsupported operand type(s) for | (unsupported-binary-operation)
        - id: ruff
          types_or: [ python, pyi, jupyter ]
          exclude: (/test_|tests/|docs/|notebooks/)
          args: [ --fix ]
        # Formats Python, Pyi, and Jupyter files, excluding specified directories
        - id: ruff-format
          types_or: [ python, pyi, jupyter ]
          exclude: (docs/|/tests/)
          args: [ --quiet ]

      # Used to have proper type annotations for library code.
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
          - id: mypy
            # You can add additional plugins for mypy below
            # such as types-python-dateutil
            additional_dependencies: [pydantic>=2.8.2, types-pyyaml>=6.0.12]
            exclude: (/test_|setup.py|/tests/|docs/)

